### ISSUE TITLE
Escaped characters in URL paths and query strings may not be delivered correctly?

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-publish-vercel#20]
Initially, I thought this bug was "Tables AND row primary keys with / in result in 404s"

Refs #5.

This is a page where the primary key value contains an encoded `/` - it 404s:
https://til.simonwillison.net/til/til/python%2Fconvert-to-utc-without-pytz.md

So does https://datasette-public.now.sh/fixtures/table%2Fwith%2Fslashes.csv

**Comment by simonw** [comment]
My hunch is that this is a limitation of AWS lambda - it looks like it might be decoding those escaped paths before they reach the lambda function.

**Comment by styfle** [comment]
Perhaps the ASGI implementation is wrong here: https://github.com/zeit/now/blob/master/packages/now-python/now_init.py#L258

**Comment by simonw** [comment]
Oh great spot! I'll have a look at that and maybe send a pull request.

**Comment by simonw** [comment]
I'm suspicious that this goes beyond just `/` characters - see https://github.com/simonw/datasette/issues/736 and https://github.com/simonw/datasette/issues/735

**Comment by simonw** [comment]
Dupe of #28
