### ISSUE TITLE
Running --generate-dir not creating directory

### ISSUE THREAD

**Issue by mccomaschris** [simonw/datasette-publish-vercel#27]
I'm attempting to run --generate-dir. I get confirmation it was created, but when I review the directory it's not actually there. See attached screenshot.

<img width="949" alt="Screen Shot 2020-08-11 at 1 19 12 PM" src="https://user-images.githubusercontent.com/26128/89928101-4fb4fe00-dbd5-11ea-9664-11d98d235682.png">

**Comment by simonw** [comment]
Yes, this is a bug. That option does work if you provide a full directory path - I always use `--generate-dir /tmp/foo` which is why I hadn't spotted it before.
