### ISSUE TITLE
UTF-8 problem

### ISSUE THREAD

**Issue by dofbi** [simonw/datasette-publish-vercel#29]
Hello,
I have facing some utf-8 problem after deployment on vercel

![Capture du 2020-12-06 02-45-53](https://user-images.githubusercontent.com/84446/101270088-94a90580-376d-11eb-9d81-a83491aa2409.png)
**on vercel**

![Capture du 2020-12-06 02-46-32](https://user-images.githubusercontent.com/84446/101270096-a68aa880-376d-11eb-965b-f123d210f374.png)
locally with Docker image

**Comment by simonw** [comment]
That's really strange. Could you share a copy of the database file you are trying to deploy, or a subset that illustrates the bug?

**Comment by dofbi** [comment]
Hello @simonw 
you can download here https://ayim.vercel.app/ayim.db

By the way, thank for your great work to **Datasette**

**Comment by jokull** [comment]
Running into the same problem. [Here is the instance](https://namsbrautir.vercel.app).

**Comment by simonw** [comment]
Good news - this is fixed by the change in #28. https://ayim-bug-test.vercel.app/ayim/Carto-FR?Pays=S%C3%A9n%C3%A9gal

**Comment by dofbi** [comment]
Very good news 👏🏾👍🏾@simonw 🎖️
