### ISSUE TITLE
Usage with GitHub Actions

### ISSUE THREAD

**Issue by loleg** [simonw/datasette-publish-vercel#36]
It would be great if the README clarified how to use Vercel project/org tokens to run the publish step as part of a GitHub Action - or, how this plugin could be used in combination with the actively maintained https://github.com/BetaHuhn/deploy-to-vercel-action

**Comment by simonw** [comment]
This is a great idea - I'll add this to the README.

**Comment by simonw** [comment]
https://github.com/simonw/datasette-publish-vercel/blob/main/README.md#using-this-with-github-actions

**Comment by loleg** [comment]
Thanks @simonw ! :man_dancing:
