### ISSUE TITLE
Ability to specify a custom vercel.json

### ISSUE THREAD

**Issue by mroswell** [simonw/datasette-publish-vercel#51]
I'm trying to resolve this issue:
https://github.com/simonw/datasette/issues/1284

Vercel suggested placing this in vercel.json:
```
  "rewrites": [
    { "source": "/", "destination": "/disinfectants/listN" },
  ]
```
But datasette-publish-vercel seems to completely overwrite vercel.json in __init__.py (lines 204 - 212)

How would I add the above rewrites key to vercel.json?

Even though the rewrites key is in my root vercel.json file, it doesn't show up on Vercel, presumably because of that json.dumps in __init__.py.

(I don't know if their rewrites approach would work... but seems worth a try, if I could figure out how.)

**Comment by simonw** [comment]
It makes sense to me that this tool would allow you to provide your own version of the `vercel.json` file - the logic for merging two files is a little too complicated I think, but instead the tool could dump out the version it _would_ use, allow you to edit it and then let you pass it as an argument - something like this:

    datasette publish vercel my-database.db --project=my-database --dump-vercel-json > vercel.json
    # Now you edit that file
    datasette publish vercel my-database.db --project=my-database --vercel-json vercel.json

**Comment by styfle** [comment]
There's a new API designed to avoid this problem: https://vercel.com/docs/file-system-api

Basically, the framework would write files to `.output` directory and never touch the vercel.json file.
